config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get    'help'   => 'static_pages#help'
  get    'signup' => 'users#new'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  get    'logout' => 'sessions#destroy'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]

end

app/views/layouts/_footer.html.erb
<footer class="footer row">
  <div class="small-12 columns">
    <div class="icon-bar five-up">
      <%= link_to '#', class: 'item' do %>
        <i class="fi-torsos-all"></i>
        <label>Players</label>
      <% end %>
      <%= link_to '#', class: 'item' do %>
        <i class="fi-trophy"></i>
        <label>Standings</label>
      <% end %>
      <%= link_to '#', class: 'item' do %>
        <i class="fi-foot"></i>
        <label>Tournament</label>
      <% end %>
      <%= link_to help_path, class: 'item' do %>
        <i class="fi-info"></i>
        <label>Help</label>
      <% end %>
      <%= link_to '#', class: 'item' do %>
        <i class="fi-wrench"></i>
        <label>Admin</label>
      <% end %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="contain-to-grid fixed">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to 'Foosball', root_path %></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li><%= nav_link_to 'Home', root_path, {}, { wrapper: 'li' } %></li>
          <li><%= nav_link_to 'Test', '#', {}, { wrapper: 'li' } %></li>
          <li class="has-dropdown">
            <%= link_to 'Teams', '#' %>
            <ul class="dropdown">
              <li><%= nav_link_to 'Randomize Teams', '#', {}, { wrapper: 'li' } %></li>
              <li><%= nav_link_to 'Show Teams', '#', {}, { wrapper: 'li' } %></li>
            </ul>
          </li>
          <li><%= nav_link_to 'Players', '#', {}, { wrapper: 'li' } %></li>
        </ul>
      </section>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag    "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="row">
      <div id="content" class="small-12 columns">
      <% if !flash.empty? %>
        <div id="flash_content" class="row">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "small-7 small-centered text-center columns alert-box #{message_type}", html: { 'data-alert' => true }) %>
        <% end %>
        </div>
      <% end %>

        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>

    <% if Rails.env.development? %>
    <div id="debug_dump" class="row">
      <div class="small-12 columns panel radius">
        <%= debug(params) %>
      </div>
    </div>
    <% end %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  </body>
</html>